#!/usr/bin/env python3
"""千千 4年级词汇例句库 — 每个词配一句简单例句（4年级水平，用词尽量简单）"""

# 格式: {en: (英文例句, 中文翻译)}
# 例句原则: 一般现在时、主语用 I/we/you/he/she/it/they/常见名词、词数 3-8 个、单词尽量是学过的
EXAMPLES = {
    # ── 数字 ──
    "one": ("I have one apple.", "我有一个苹果。"),
    "two": ("I can see two cats.", "我能看到两只猫。"),
    "three": ("I have three books.", "我有三本书。"),
    "four": ("There are four chairs.", "有四把椅子。"),
    "five": ("I have five fingers.", "我有五根手指。"),
    "six": ("I get up at six.", "我六点起床。"),
    "seven": ("We have seven days in a week.", "一周有七天。"),
    "eight": ("I have eight pens.", "我有八支钢笔。"),
    "nine": ("I am nine years old.", "我九岁了。"),
    "ten": ("I have ten toes.", "我有十个脚趾。"),
    "eleven": ("There are eleven students.", "有十一个学生。"),
    "twelve": ("There are twelve months in a year.", "一年有十二个月。"),
    "thirteen": ("I have thirteen crayons.", "我有十三支蜡笔。"),
    "fourteen": ("There are fourteen desks.", "有十四张书桌。"),
    "fifteen": ("I can count to fifteen.", "我能数到十五。"),
    "sixteen": ("My sister is sixteen.", "我姐姐十六岁。"),
    "seventeen": ("There are seventeen boys.", "有十七个男孩。"),
    "eighteen": ("I have eighteen books.", "我有十八本书。"),
    "nineteen": ("There are nineteen girls.", "有十九个女孩。"),
    "twenty": ("I have twenty stickers.", "我有二十张贴纸。"),
    "thirty": ("My father is thirty.", "我爸爸三十岁。"),
    "forty": ("There are forty students.", "有四十个学生。"),
    "fifty": ("The book is fifty yuan.", "这本书五十元。"),
    "hundred": ("I have one hundred yuan.", "我有一百元。"),
    # ── 颜色 ──
    "red": ("My bag is red.", "我的书包是红色的。"),
    "yellow": ("The banana is yellow.", "香蕉是黄色的。"),
    "green": ("The grass is green.", "草是绿色的。"),
    "blue": ("The sky is blue.", "天空是蓝色的。"),
    "black": ("I like the black cat.", "我喜欢那只黑猫。"),
    "brown": ("My shoes are brown.", "我的鞋子是棕色的。"),
    "white": ("The snow is white.", "雪是白色的。"),
    "orange": ("The orange is orange.", "这个橙子是橙色的。"),
    "pink": ("My dress is pink.", "我的连衣裙是粉色的。"),
    "purple": ("I like purple grapes.", "我喜欢紫色的葡萄。"),
    "grey": ("The elephant is grey.", "大象是灰色的。"),
    # ── 文具/学习用品 ──
    "ruler": ("I have a long ruler.", "我有一把长尺子。"),
    "eraser": ("This is my eraser.", "这是我的橡皮。"),
    "pencil": ("I write with a pencil.", "我用铅笔写字。"),
    "crayon": ("I draw with crayons.", "我用蜡笔画画。"),
    "bag": ("My bag is heavy.", "我的书包很重。"),
    "pen": ("I have a blue pen.", "我有一支蓝笔。"),
    "pencil box": ("My pencil box is new.", "我的铅笔盒是新的。"),
    "book": ("I read a book.", "我读一本书。"),
    "notebook": ("This is my notebook.", "这是我的笔记本。"),
    "storybook": ("I like storybooks.", "我喜欢故事书。"),
    "schoolbag": ("My schoolbag is big.", "我的书包很大。"),
    "sharpener": ("I use a sharpener.", "我用卷笔刀。"),
    "glue": ("I need some glue.", "我需要一些胶水。"),
    "scissors": ("The scissors are sharp.", "剪刀很锋利。"),
    "paper": ("I draw on paper.", "我在纸上画画。"),
    "dictionary": ("I use a dictionary.", "我使用词典。"),
    "map": ("Look at the map.", "看这张地图。"),
    # ── 身体部位 ──
    "head": ("Touch your head.", "摸摸你的头。"),
    "face": ("Wash your face.", "洗洗你的脸。"),
    "nose": ("My nose is small.", "我的鼻子很小。"),
    "mouth": ("Open your mouth.", "张开你的嘴。"),
    "eye": ("I have two eyes.", "我有两只眼睛。"),
    "ear": ("My ears are big.", "我的耳朵很大。"),
    "arm": ("Raise your arms.", "举起你的胳膊。"),
    "hand": ("Wash your hands.", "洗洗你的手。"),
    "leg": ("My legs are long.", "我的腿很长。"),
    "foot": ("My foot hurts.", "我的脚疼。"),
    "body": ("My body is strong.", "我的身体很强壮。"),
    "hair": ("Her hair is long.", "她的头发很长。"),
    "finger": ("I have ten fingers.", "我有十根手指。"),
    "toe": ("I have ten toes.", "我有十个脚趾。"),
    "knee": ("Bend your knees.", "弯弯你的膝盖。"),
    "shoulder": ("Touch your shoulders.", "摸摸你的肩膀。"),
    # ── 动物 ──
    "cat": ("The cat is cute.", "猫很可爱。"),
    "dog": ("I have a dog.", "我有一只狗。"),
    "duck": ("The duck can swim.", "鸭子会游泳。"),
    "pig": ("The pig is fat.", "猪很胖。"),
    "bear": ("The bear is big.", "熊很大。"),
    "elephant": ("The elephant has a long nose.", "大象有长鼻子。"),
    "monkey": ("The monkey likes bananas.", "猴子喜欢香蕉。"),
    "bird": ("The bird can fly.", "鸟会飞。"),
    "tiger": ("The tiger is strong.", "老虎很强壮。"),
    "panda": ("The panda is black and white.", "熊猫是黑白色的。"),
    "zoo": ("We go to the zoo.", "我们去动物园。"),
    "fish": ("Fish can swim.", "鱼会游泳。"),
    "rabbit": ("The rabbit has long ears.", "兔子有长耳朵。"),
    "mouse": ("The mouse is small.", "老鼠很小。"),
    "horse": ("The horse can run fast.", "马跑得很快。"),
    "cow": ("The cow gives milk.", "奶牛产奶。"),
    "sheep": ("The sheep is white.", "绵羊是白色的。"),
    "hen": ("The hen has eggs.", "母鸡下蛋。"),
    "goat": ("The goat likes grass.", "山羊喜欢草。"),
    "chicken": ("The chicken is yellow.", "小鸡是黄色的。"),
    "frog": ("The frog can jump.", "青蛙会跳。"),
    "snake": ("The snake is long.", "蛇很长。"),
    # ── 食物与饮料 ──
    "bread": ("I eat bread for breakfast.", "我早餐吃面包。"),
    "juice": ("I like apple juice.", "我喜欢苹果汁。"),
    "egg": ("I eat an egg.", "我吃一个鸡蛋。"),
    "milk": ("I drink milk every day.", "我每天喝牛奶。"),
    "water": ("I want some water.", "我想要一些水。"),
    "cake": ("The cake is sweet.", "蛋糕很甜。"),
    "rice": ("We eat rice for lunch.", "我们午饭吃米饭。"),
    "beef": ("I like beef noodles.", "我喜欢牛肉面。"),
    "noodles": ("I eat noodles for dinner.", "我晚饭吃面条。"),
    "soup": ("The soup is hot.", "汤很热。"),
    "vegetable": ("Eat more vegetables.", "多吃蔬菜。"),
    "chopsticks": ("I can use chopsticks.", "我会用筷子。"),
    "bowl": ("There is a bowl on the table.", "桌上有一个碗。"),
    "fork": ("I eat with a fork.", "我用叉子吃。"),
    "knife": ("The knife is sharp.", "刀很锋利。"),
    "spoon": ("I need a spoon.", "我需要一个勺子。"),
    "hamburger": ("I want a hamburger.", "我想要一个汉堡包。"),
    "hot dog": ("I have a hot dog.", "我有一个热狗。"),
    "ice cream": ("The ice cream is cold.", "冰淇淋很冰。"),
    "tea": ("I drink tea.", "我喝茶。"),
    "coffee": ("My father likes coffee.", "我爸爸喜欢咖啡。"),
    "candy": ("Don't eat too much candy.", "不要吃太多糖果。"),
    "sandwich": ("I have a sandwich for lunch.", "我午饭吃一个三明治。"),
    "dumpling": ("I like dumplings.", "我喜欢饺子。"),
    # ── 水果与蔬菜 ──
    "apple": ("The apple is red.", "苹果是红色的。"),
    "pear": ("The pear is sweet.", "梨很甜。"),
    "banana": ("The banana is yellow.", "香蕉是黄色的。"),
    "orange": ("I eat an orange.", "我吃一个橙子。"),
    "grape": ("The grapes are purple.", "葡萄是紫色的。"),
    "watermelon": ("The watermelon is big.", "西瓜很大。"),
    "strawberry": ("I like strawberries.", "我喜欢草莓。"),
    "tomato": ("The tomato is red.", "西红柿是红色的。"),
    "potato": ("I like potatoes.", "我喜欢土豆。"),
    "carrot": ("The rabbit likes carrots.", "兔子喜欢胡萝卜。"),
    "onion": ("Cut the onion.", "切洋葱。"),
    "green beans": ("I like green beans.", "我喜欢豆角。"),
    # ── 家庭成员与人物 ──
    "father": ("My father is a doctor.", "我爸爸是医生。"),
    "mother": ("My mother is kind.", "我妈妈很善良。"),
    "brother": ("My brother is tall.", "我哥哥很高。"),
    "sister": ("My sister is cute.", "我妹妹很可爱。"),
    "grandpa": ("My grandpa is old.", "我爷爷年纪大了。"),
    "grandma": ("My grandma cooks well.", "我奶奶做饭好吃。"),
    "family": ("I love my family.", "我爱我的家。"),
    "uncle": ("My uncle lives in Beijing.", "我叔叔住在北京。"),
    "aunt": ("My aunt is a nurse.", "我姑姑是护士。"),
    "cousin": ("My cousin is my friend.", "我表弟是我的朋友。"),
    "baby": ("The baby is sleeping.", "婴儿在睡觉。"),
    "boy": ("The boy is my friend.", "这个男孩是我的朋友。"),
    "girl": ("The girl can sing.", "这个女孩会唱歌。"),
    "man": ("The man is strong.", "这个男人很强壮。"),
    "woman": ("The woman is beautiful.", "这个女人很漂亮。"),
    "friend": ("She is my friend.", "她是我的朋友。"),
    "teacher": ("My teacher is nice.", "我的老师很好。"),
    "student": ("I am a student.", "我是学生。"),
    "people": ("Many people like it.", "很多人喜欢它。"),
    # ── 职业 ──
    "doctor": ("The doctor helps people.", "医生帮助人们。"),
    "nurse": ("The nurse is busy.", "护士很忙。"),
    "driver": ("The driver drives a bus.", "司机开公交车。"),
    "farmer": ("The farmer has a farm.", "农民有一个农场。"),
    "worker": ("The worker works hard.", "工人努力工作。"),
    "cook": ("The cook makes food.", "厨师做食物。"),
    "singer": ("She is a singer.", "她是一名歌手。"),
    "writer": ("He is a writer.", "他是一名作家。"),
    "policeman": ("The policeman is tall.", "警察很高。"),
    # ── 交通工具 ──
    "bus": ("I go to school by bus.", "我坐公交车上学。"),
    "bike": ("I ride a bike.", "我骑自行车。"),
    "taxi": ("We take a taxi.", "我们坐出租车。"),
    "car": ("My father has a car.", "我爸爸有一辆车。"),
    "train": ("The train is fast.", "火车很快。"),
    "ship": ("The ship is on the sea.", "船在海上。"),
    "plane": ("The plane can fly.", "飞机会飞。"),
    "boat": ("There is a boat on the lake.", "湖上有一只小船。"),
    "subway": ("I go to work by subway.", "我坐地铁上班。"),
    "truck": ("The truck is big.", "卡车很大。"),
    # ── 教室与学校 ──
    "classroom": ("Our classroom is big.", "我们的教室很大。"),
    "window": ("Open the window.", "打开窗户。"),
    "blackboard": ("Look at the blackboard.", "看黑板。"),
    "light": ("Turn on the light.", "开灯。"),
    "picture": ("The picture is nice.", "这幅画很漂亮。"),
    "door": ("Close the door.", "关门。"),
    "computer": ("I play games on the computer.", "我在电脑上玩游戏。"),
    "fan": ("The fan is on.", "风扇开着。"),
    "wall": ("The wall is white.", "墙是白色的。"),
    "floor": ("The floor is clean.", "地板很干净。"),
    "desk": ("My desk is new.", "我的书桌是新的。"),
    "chair": ("Sit on the chair.", "坐在椅子上。"),
    "school": ("I go to school at seven.", "我七点去上学。"),
    "playground": ("We play on the playground.", "我们在操场上玩。"),
    "library": ("I read in the library.", "我在图书馆读书。"),
    "homework": ("I do my homework.", "我做作业。"),
    "grade": ("I am in Grade Four.", "我上四年级。"),
    "bell": ("The bell rings.", "铃响了。"),
    # ── 家与房间 ──
    "home": ("I go home at five.", "我五点回家。"),
    "room": ("My room is clean.", "我的房间很干净。"),
    "bedroom": ("I sleep in my bedroom.", "我在卧室睡觉。"),
    "living room": ("We watch TV in the living room.", "我们在客厅看电视。"),
    "study": ("I read in the study.", "我在书房读书。"),
    "kitchen": ("Mum is in the kitchen.", "妈妈在厨房。"),
    "bathroom": ("I wash my face in the bathroom.", "我在浴室洗脸。"),
    "bed": ("I sleep on the bed.", "我睡在床上。"),
    "phone": ("The phone is on the table.", "电话在桌子上。"),
    "table": ("The food is on the table.", "食物在桌子上。"),
    "sofa": ("The cat is on the sofa.", "猫在沙发上。"),
    "fridge": ("The milk is in the fridge.", "牛奶在冰箱里。"),
    "shelf": ("The books are on the shelf.", "书在架子上。"),
    "TV": ("We watch TV.", "我们看电视。"),
    "clock": ("The clock is on the wall.", "钟在墙上。"),
    "lamp": ("The lamp is on the desk.", "台灯在书桌上。"),
    "key": ("This is my key.", "这是我的钥匙。"),
    # ── 衣服 ──
    "shirt": ("I wear a white shirt.", "我穿一件白衬衫。"),
    "T-shirt": ("I like this T-shirt.", "我喜欢这件T恤。"),
    "skirt": ("Her skirt is pink.", "她的裙子是粉色的。"),
    "dress": ("The dress is beautiful.", "这条连衣裙很漂亮。"),
    "jacket": ("Put on your jacket.", "穿上你的夹克。"),
    "coat": ("Put on your coat.", "穿上你的外套。"),
    "sweater": ("This sweater is warm.", "这件毛衣很暖和。"),
    "shoes": ("My shoes are black.", "我的鞋子是黑色的。"),
    "socks": ("I wear white socks.", "我穿白袜子。"),
    "shorts": ("He wears shorts in summer.", "他夏天穿短裤。"),
    "pants": ("These pants are long.", "这条裤子很长。"),
    "hat": ("I have a red hat.", "我有一顶红帽子。"),
    "cap": ("He wears a cap.", "他戴着一顶帽子。"),
    "gloves": ("Put on your gloves.", "戴上你的手套。"),
    "scarf": ("The scarf is warm.", "围巾很暖和。"),
    "jeans": ("I like blue jeans.", "我喜欢蓝色牛仔裤。"),
    # ── 天气与自然 ──
    "weather": ("How is the weather?", "天气怎么样？"),
    "cold": ("It is cold today.", "今天很冷。"),
    "cool": ("It is cool in autumn.", "秋天很凉爽。"),
    "warm": ("It is warm in spring.", "春天很温暖。"),
    "hot": ("It is hot in summer.", "夏天很热。"),
    "sunny": ("It is sunny today.", "今天阳光明媚。"),
    "windy": ("It is windy today.", "今天有风。"),
    "cloudy": ("It is cloudy today.", "今天多云。"),
    "snowy": ("It is snowy in winter.", "冬天下雪。"),
    "rainy": ("It is rainy today.", "今天下雨。"),
    "foggy": ("It is foggy in the morning.", "早上有雾。"),
    "sun": ("The sun is bright.", "太阳很明亮。"),
    "moon": ("The moon is big tonight.", "今晚月亮很大。"),
    "star": ("I see stars at night.", "我晚上看到星星。"),
    "sky": ("The sky is blue.", "天空是蓝色的。"),
    "cloud": ("The cloud is white.", "云是白色的。"),
    "rain": ("It will rain.", "要下雨了。"),
    "snow": ("The snow is white.", "雪是白色的。"),
    "wind": ("The wind is strong.", "风很大。"),
    "tree": ("The tree is tall.", "树很高。"),
    "flower": ("The flower is red.", "花是红色的。"),
    "grass": ("The grass is green.", "草是绿色的。"),
    "river": ("The river is long.", "河流很长。"),
    "lake": ("We swim in the lake.", "我们在湖里游泳。"),
    "sea": ("The sea is blue.", "大海是蓝色的。"),
    "mountain": ("The mountain is high.", "山很高。"),
    "hill": ("The hill is small.", "小山很小。"),
    # ── 时间 ──
    "time": ("What time is it?", "几点了？"),
    "o'clock": ("It is three o'clock.", "现在三点钟。"),
    "morning": ("Good morning.", "早上好。"),
    "afternoon": ("Good afternoon.", "下午好。"),
    "evening": ("Good evening.", "晚上好。"),
    "night": ("Good night.", "晚安。"),
    "today": ("It is hot today.", "今天很热。"),
    "week": ("There are seven days in a week.", "一周有七天。"),
    "day": ("Have a nice day.", "祝你今天愉快。"),
    "year": ("Happy New Year.", "新年快乐。"),
    "month": ("There are twelve months in a year.", "一年有十二个月。"),
    "hour": ("I watch TV for an hour.", "我看一小时电视。"),
    "minute": ("Wait a minute.", "等一下。"),
    "Monday": ("I go to school on Monday.", "我星期一去上学。"),
    "Tuesday": ("We have art on Tuesday.", "我们星期二有美术课。"),
    "Wednesday": ("It is Wednesday today.", "今天是星期三。"),
    "Thursday": ("I play football on Thursday.", "我星期四踢足球。"),
    "Friday": ("We have English on Friday.", "我们星期五有英语课。"),
    "Saturday": ("I play with friends on Saturday.", "我星期六和朋友玩。"),
    "Sunday": ("We have a picnic on Sunday.", "我们星期天去野餐。"),
    "spring": ("Flowers bloom in spring.", "春天花开了。"),
    "summer": ("We swim in summer.", "我们夏天游泳。"),
    "autumn": ("Leaves fall in autumn.", "秋天树叶落下。"),
    "winter": ("It snows in winter.", "冬天下雪。"),
    # ── 动词 ──
    "be": ("I want to be a teacher.", "我想成为一名老师。"),
    "am": ("I am happy.", "我很开心。"),
    "is": ("She is my sister.", "她是我的姐姐。"),
    "are": ("You are my friend.", "你是我的朋友。"),
    "have": ("I have a new bag.", "我有一个新书包。"),
    "has": ("She has long hair.", "她有长头发。"),
    "do": ("I do my homework.", "我做作业。"),
    "does": ("She does her homework.", "她做作业。"),
    "clean": ("I clean my room.", "我打扫我的房间。"),
    "help": ("Can you help me?", "你能帮我吗？"),
    "open": ("Open your book.", "打开你的书。"),
    "close": ("Close your eyes.", "闭上眼睛。"),
    "read": ("I read a story.", "我读一个故事。"),
    "write": ("I write a letter.", "我写一封信。"),
    "draw": ("I draw a tree.", "我画一棵树。"),
    "sing": ("She sings a song.", "她唱一首歌。"),
    "dance": ("We dance at the party.", "我们在聚会上跳舞。"),
    "play": ("I play with my dog.", "我和我的狗玩。"),
    "run": ("I run fast.", "我跑得快。"),
    "jump": ("The cat can jump.", "猫会跳。"),
    "swim": ("I swim in the sea.", "我在海里游泳。"),
    "walk": ("I walk to school.", "我走路去上学。"),
    "fly": ("The bird can fly.", "鸟会飞。"),
    "eat": ("I eat an apple.", "我吃一个苹果。"),
    "drink": ("I drink milk.", "我喝牛奶。"),
    "like": ("I like bananas.", "我喜欢香蕉。"),
    "want": ("I want some water.", "我想要一些水。"),
    "go": ("Let's go to school.", "我们去上学吧。"),
    "come": ("Come here, please.", "请过来。"),
    "see": ("I see a bird.", "我看到一只鸟。"),
    "look": ("Look at the picture.", "看这幅画。"),
    "listen": ("Listen to the teacher.", "听老师讲。"),
    "speak": ("I speak Chinese.", "我说中文。"),
    "say": ("Say hello to your teacher.", "向你的老师问好。"),
    "tell": ("Tell me a story.", "给我讲个故事。"),
    "ask": ("I ask a question.", "我问一个问题。"),
    "answer": ("Please answer the question.", "请回答问题。"),
    "sit": ("Sit down, please.", "请坐。"),
    "stand": ("Stand up, please.", "请起立。"),
    "sleep": ("The baby sleeps.", "婴儿在睡觉。"),
    "cook": ("Mum cooks dinner.", "妈妈做晚饭。"),
    "wash": ("I wash my hands.", "我洗手。"),
    "watch": ("I watch TV.", "我看电视。"),
    "work": ("My father works in a hospital.", "我爸爸在医院工作。"),
    "study": ("I study English.", "我学英语。"),
    "learn": ("We learn new words.", "我们学新单词。"),
    "know": ("I know the answer.", "我知道答案。"),
    "think": ("I think it is good.", "我觉得它很好。"),
    "give": ("Give me the book.", "把书给我。"),
    "take": ("Take your bag.", "带上你的书包。"),
    "put": ("Put on your coat.", "穿上你的外套。"),
    "get": ("I get up at six.", "我六点起床。"),
    "make": ("I make a cake.", "我做蛋糕。"),
    "let": ("Let me help you.", "让我帮你。"),
    "can": ("I can swim.", "我会游泳。"),
    "may": ("May I come in?", "我可以进来吗？"),
    "must": ("You must go now.", "你现在必须走。"),
    "please": ("Sit down, please.", "请坐。"),
    "thank": ("Thank you very much.", "非常感谢。"),
    # ── 形容词 ──
    "tall": ("My father is tall.", "我爸爸很高。"),
    "short": ("The pencil is short.", "这支铅笔很短。"),
    "thin": ("The boy is thin.", "这个男孩很瘦。"),
    "strong": ("He is strong.", "他很强壮。"),
    "quiet": ("Be quiet, please.", "请安静。"),
    "cute": ("The baby is cute.", "婴儿很可爱。"),
    "friendly": ("She is friendly.", "她很友好。"),
    "big": ("The elephant is big.", "大象很大。"),
    "small": ("The mouse is small.", "老鼠很小。"),
    "long": ("My hair is long.", "我的头发很长。"),
    "nice": ("You are nice.", "你很好。"),
    "good": ("I am a good student.", "我是好学生。"),
    "bad": ("It is bad for you.", "这对你不好。"),
    "happy": ("I am happy today.", "我今天很开心。"),
    "sad": ("The boy is sad.", "这个男孩很难过。"),
    "new": ("I have a new pen.", "我有一支新笔。"),
    "old": ("My grandpa is old.", "我爷爷年纪大了。"),
    "young": ("My teacher is young.", "我的老师很年轻。"),
    "fat": ("The pig is fat.", "猪很胖。"),
    "heavy": ("The box is heavy.", "箱子很重。"),
    "light": ("The bag is light.", "书包很轻。"),
    "cheap": ("The toy is cheap.", "这个玩具很便宜。"),
    "expensive": ("The car is expensive.", "这辆车很贵。"),
    "beautiful": ("The flower is beautiful.", "花很美丽。"),
    "clever": ("The monkey is clever.", "猴子很聪明。"),
    "tired": ("I am tired.", "我累了。"),
    "hungry": ("I am hungry.", "我饿了。"),
    "thirsty": ("I am thirsty.", "我渴了。"),
    "sick": ("He is sick.", "他生病了。"),
    "funny": ("The story is funny.", "这个故事很有趣。"),
    "great": ("That's great!", "太棒了！"),
    "wonderful": ("The party is wonderful.", "聚会很棒。"),
    "delicious": ("The cake is delicious.", "蛋糕很好吃。"),
    "fast": ("The horse runs fast.", "马跑得快。"),
    "slow": ("The turtle is slow.", "乌龟很慢。"),
    "wet": ("My shoes are wet.", "我的鞋子湿了。"),
    "dry": ("The clothes are dry.", "衣服干了。"),
    "dirty": ("My hands are dirty.", "我的手脏了。"),
    "empty": ("The bottle is empty.", "瓶子空了。"),
    "full": ("The cup is full.", "杯子满了。"),
    "easy": ("It is easy.", "这很容易。"),
    "difficult": ("It is difficult.", "这很难。"),
    "safe": ("This place is safe.", "这个地方很安全。"),
    "dangerous": ("It is dangerous.", "这很危险。"),
    "right": ("You are right.", "你是对的。"),
    "wrong": ("It is wrong.", "这是错的。"),
    "busy": ("My mother is busy.", "我妈妈很忙。"),
    "free": ("I am free today.", "我今天有空。"),
    "ready": ("Are you ready?", "你准备好了吗？"),
    # ── 代词 ──
    "I": ("I am a girl.", "我是一个女孩。"),
    "you": ("You are my friend.", "你是我的朋友。"),
    "he": ("He is my brother.", "他是我的哥哥。"),
    "she": ("She is my sister.", "她是我的姐姐。"),
    "it": ("It is a cat.", "它是一只猫。"),
    "we": ("We are students.", "我们是学生。"),
    "they": ("They are my friends.", "他们是我的朋友。"),
    "my": ("This is my book.", "这是我的书。"),
    "your": ("Is this your bag?", "这是你的书包吗？"),
    "his": ("His name is Tom.", "他的名字是汤姆。"),
    "her": ("Her hair is long.", "她的头发很长。"),
    "our": ("Our school is big.", "我们的学校很大。"),
    "their": ("Their house is new.", "他们的房子是新的。"),
    "me": ("Give me the pen.", "把笔给我。"),
    "him": ("I like him.", "我喜欢他。"),
    "us": ("Let us play.", "让我们玩吧。"),
    "them": ("I see them.", "我看到他们。"),
    "this": ("This is a desk.", "这是一张书桌。"),
    "that": ("That is a cat.", "那是一只猫。"),
    "these": ("These are apples.", "这些是苹果。"),
    "those": ("Those are pears.", "那些是梨。"),
    "some": ("I have some books.", "我有一些书。"),
    "any": ("Do you have any water?", "你有水吗？"),
    "all": ("All the students are here.", "所有的学生都在这。"),
    "what": ("What is this?", "这是什么？"),
    "where": ("Where is my bag?", "我的书包在哪里？"),
    "who": ("Who is she?", "她是谁？"),
    "whose": ("Whose pen is this?", "这是谁的笔？"),
    "when": ("When do you get up?", "你什么时候起床？"),
    "why": ("Why are you sad?", "你为什么难过？"),
    "how": ("How are you?", "你好吗？"),
    # ── 方位 ──
    "in": ("The book is in the bag.", "书在书包里。"),
    "on": ("The cat is on the sofa.", "猫在沙发上。"),
    "under": ("The ball is under the desk.", "球在书桌下面。"),
    "behind": ("The dog is behind the door.", "狗在门后面。"),
    "near": ("The school is near my home.", "学校在我家附近。"),
    "next to": ("My desk is next to the window.", "我的书桌在窗户旁边。"),
    "in front of": ("The teacher is in front of the blackboard.", "老师在黑板前面。"),
    "between": ("The ball is between the chairs.", "球在两把椅子之间。"),
    "left": ("Turn left.", "向左转。"),
    "right": ("Turn right.", "向右转。"),
    "here": ("Come here.", "来这里。"),
    "there": ("The book is there.", "书在那里。"),
    # ── 其他常用 ──
    "hello": ("Hello, I am Amy.", "你好，我是艾米。"),
    "hi": ("Hi, Tom!", "嗨，汤姆！"),
    "goodbye": ("Goodbye, teacher.", "再见，老师。"),
    "yes": ("Yes, I do.", "是的，我…。"),
    "no": ("No, it isn't.", "不，它不是。"),
    "sorry": ("I am sorry.", "对不起。"),
    "OK": ("OK, let's go.", "好的，我们走吧。"),
    "very": ("It is very hot.", "天气很热。"),
    "too": ("I like it too.", "我也喜欢它。"),
    "also": ("I also like milk.", "我也喜欢牛奶。"),
    "now": ("Let's go now.", "我们现在走吧。"),
    "and": ("I like apples and bananas.", "我喜欢苹果和香蕉。"),
    "but": ("I like it, but it is expensive.", "我喜欢它，但它很贵。"),
    "or": ("Do you want tea or juice?", "你想要茶还是果汁？"),
    "so": ("It is cold, so I wear a coat.", "天很冷，所以我穿外套。"),
    "because": ("I like it because it is cute.", "我喜欢它因为它很可爱。"),
    "then": ("First wash your hands, then eat.", "先洗手，再吃饭。"),
    "often": ("I often read books.", "我经常读书。"),
    "always": ("I always get up early.", "我总是早起。"),
    "usually": ("I usually walk to school.", "我通常走路去学校。"),
    "sometimes": ("I sometimes play chess.", "我有时下棋。"),
    "never": ("I never eat candy at night.", "我晚上从不吃糖果。"),
    "name": ("My name is Lily.", "我的名字是莉莉。"),
    "age": ("What is your age?", "你多大了？"),
    "number": ("My number is three.", "我的号码是三。"),
    "colour": ("What colour is it?", "它是什么颜色？"),
    "toy": ("I have a toy car.", "我有一个玩具车。"),
    "doll": ("The doll is beautiful.", "娃娃很漂亮。"),
    "kite": ("I fly a kite.", "我放风筝。"),
    "ball": ("Throw the ball.", "扔球。"),
    "game": ("We play a game.", "我们玩游戏。"),
    "sport": ("I like sports.", "我喜欢运动。"),
    "football": ("I play football.", "我踢足球。"),
    "basketball": ("He plays basketball.", "他打篮球。"),
    "tennis": ("I play tennis.", "我打网球。"),
    "swimming": ("I like swimming.", "我喜欢游泳。"),
    "party": ("We have a party.", "我们开派对。"),
    "picnic": ("We have a picnic.", "我们去野餐。"),
    "holiday": ("Summer holiday is coming.", "暑假要来了。"),
    "gift": ("I get a gift.", "我收到一个礼物。"),
    "present": ("The present is for you.", "这份礼物是给你的。"),
    "photo": ("Look at this photo.", "看这张照片。"),
    "story": ("I read a story.", "我读一个故事。"),
    "song": ("I sing a song.", "我唱一首歌。"),
    "music": ("I like music.", "我喜欢音乐。"),
    "Chinese": ("I speak Chinese.", "我说中文。"),
    "English": ("I learn English.", "我学英语。"),
    "maths": ("I like maths.", "我喜欢数学。"),
    "science": ("We have science today.", "我们今天有科学课。"),
    "art": ("I like art.", "我喜欢美术。"),
    "PE": ("We have PE on Friday.", "我们星期五有体育课。"),
}
